# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#	[main.params]
#	icon = "home"
#	newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Acvarium/"
	[social.params]
	icon = "brand-github"

[[social]]
identifier = "artstation"
name = "Artstation"
url = "https://www.artstation.com/evilvitjoker"
	[social.params]
	icon = "brand-artstation"

[[social]]
identifier = "youtube"
name = "Youtube"
url = "https://www.youtube.com/@fos_ua"
	[social.params]
	icon = "brand-youtube"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/vitshmorgun/"
	[social.params]
	icon = "brand-instagram"

[[social]]
identifier = "itch.io"
name = "itch.io"
url = "https://acvarium.itch.io/"
	[social.params]
	icon = "brand-itch"

[[social]]
identifier = "monobank"
name = "Monobank"
url = "https://send.monobank.ua/jar/8CwMnEXrWZ"
	[social.params]
	icon = "mono-jar"

[[social]]
identifier = "buymeacoffee"
name = "buymeacoffee"
url = "https://buymeacoffee.com/3dvit_ua"
	[social.params]
	icon = "buymeacoffee"
